# Generated by Django 3.2.8 on 2021-11-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0002_auto_20211108_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prefijo', models.CharField(max_length=3, verbose_name='prefijo')),
                ('Nombre', models.CharField(max_length=30, verbose_name='Tipo de Equipo')),
                ('Descripcion', models.CharField(max_length=100, verbose_name='descripcion')),
            ],
            options={
                'verbose_name': 'tipo',
                'verbose_name_plural': 'tipos',
                'ordering': ['Prefijo'],
            },
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['Nombre'], 'verbose_name': 'área', 'verbose_name_plural': 'áreas'},
        ),
    ]
